### ISSUE TITLE
Problemas en windows

### ISSUE THREAD

**Issue by gonzalotello** [AyerViernes/udd-tomaderamos-docs#3]
![screencapture-file-c-users-hola-desktop-udd-20toma-20de-20ramos-udd-tomaderamos-204-udd-tomaderamos-01-02-inicio-postulacion-problemas-acceso-html-1478656657672](https://cloud.githubusercontent.com/assets/22456515/20124709/43888b72-a607-11e6-812a-e0b07e7b3b4c.png)

**Comment by gonzalotello** [comment]
![screencapture-file-c-users-hola-desktop-udd-20toma-20de-20ramos-udd-tomaderamos-204-udd-tomaderamos-01-03-inicio-postulacion-encuestas-docentes-pendientes-html-1478656911977](https://cloud.githubusercontent.com/assets/22456515/20124738/72e73558-a607-11e6-8a92-3cf89928a87c.png)

**Comment by gonzalotello** [comment]
![screencapture-file-c-users-hola-desktop-udd-20toma-20de-20ramos-udd-tomaderamos-204-udd-tomaderamos-02-01-inicio-postulacion-html-1478657000581](https://cloud.githubusercontent.com/assets/22456515/20124760/9f1b0bd6-a607-11e6-9866-02fc18ea26a1.png)

**Comment by pochitax** [comment]
listoco
